---
- name: Install snapd
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - snapd

- name: Certbot - Start and enable snapd
  ansible.builtin.systemd:
    name: snapd.service
    enabled: yes
    state: started
    masked: no

- name: Install snap core
  shell: snap install core; snap refresh core
  ignore_errors: yes

- name: Install Certbot
  shell: snap install --classic certbot
  ignore_errors: yes

- name: Check that Certbot hasnt already issued a cert
  stat:
    path: /etc/letsencrypt/live/{{ nextcloud_fqdn }}
  register: certbot_cert_check

- name: Install certbot
  shell: "/snap/bin/certbot --apache --noninteractive --agree-tos
    --email {{ certbot_email }} -d {{ nextcloud_fqdn }}"
  ignore_errors: yes
  when:
    - not certbot_cert_check.stat.exists
