---
- name: Restart firewalld
  ansible.builtin.systemd:
    name: firewalld.service
    state: restarted

- name: Restart apache2
  ansible.builtin.systemd:
    name: apache2.service
    state: restarted

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban.service
    state: restarted
